// Generated by Selenium IDE
const { Builder, By, WebElementCondition,Capabilities, until, Actions } = require("selenium-webdriver")
const testdata = require('./../objects/testData')
const assert = require("assert")
const loginpage = require('../pageobjects/loginpage');
const segmentlistpage = require('../pageobjects/segmentlistpage')
const segmentCreationPage = require('../pageobjects/segmentCreationPage')
const smsEngageCreate = require ('../pageobjects/smsEngagementCreationPage')
const { drive } = require("googleapis/build/src/apis/drive");
const objt = require('../operations/ReadObjects');
const opertn = require('../operations/UIOperations');

let driver;

before(async function(){
    this.timeout(1000000)
    //this.driver = await BasePage.driver;
    this.driver = await segmentCreationPage.driver;
    //await this.driver.manage().setTimeouts({ implicit: 100000 });
    //await driver.get("https://ttl.lemnisk.co/app/login/")
    //await driver.get("https://cdp.lemnisk.co/app/login/")
    await this.driver.get(testdata.url.input.validurl)
    await this.driver.manage().window().setRect({ width: 1848, height: 1053 })
    return await driver;
});

describe('Testing Creation of sms engagement', function() {
  this.timeout(100000)
  //let driver
  let vars
  let actions
  let prop
  beforeEach(async function() {
   // driver = await new Builder().forBrowser('chrome').build()
      // Navigate to the login page
   // vars = {}
  })
  afterEach(async function() {
    //await this.driver.quit();
  })

  it('segmentlist_testCreatSMSEngage_test', async function() {
   
    this.timeout(1000000)
    prop = await objt.getObjectRepository();
    await this.driver.manage().setTimeouts({ implicit: 1000000 });
    await loginpage.log_in(testdata.username.input.validusername, testdata.password.input.validpassword,await this.driver);
    await segmentlistpage.selectAndOpenSegment("92864",await this.driver);
    await smsEngageCreate.createSMSEngagement(testdata.username.input.validusername, testdata.password.input.validpassword,await this.driver);
  })

})
