name: Selenium Tests

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Setup Chrome
        run: |
          docker pull selenium/standalone-chrome:latest
          docker run -d -p 4444:4444 selenium/standalone-chrome:latest

      - name: Update /etc/hosts
        run: |
          echo "3.230.10.186 ttl.lemnisk.co" | sudo tee -a /etc/hosts
          echo "3.230.10.186 lemniskapi2.lemnisk.co" | sudo tee -a /etc/hosts
          echo "3.230.10.186 appbackend.lemnisk.co" | sudo tee -a /etc/hosts

      - name: Run Selenium Tests
        run: npm run test
        working-directory: ${{ github.workspace }}

      - name: Debugging Information
        run: |
          echo "Current Working Directory: $(pwd)"
          echo "Contents of the ./test directory:"
          ls -R ./test
          echo "Environment Variables: ${{ toJson(env) }}"
        continue-on-error: true
