name: Selenium Tests

on:
  push:
    branches:
      - master
      
jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [21]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: 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
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
                
      - name: Install dependencies
        run: npm install

      - name: Install mocha
        run: npm install -g mocha

      - name: Check Mocha version
        run: npx mocha --version

      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages  
          
      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: target/allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
        
      - uses: browser-actions/setup-chrome@v1
      - run: chrome --version
      
      - name: Update /etc/hosts
        run: |
          echo "3.86.156.221 ttl.lemnisk.co" | sudo tee -a /etc/hosts
          echo "3.86.156.221 lemniskapi2.lemnisk.co" | sudo tee -a /etc/hosts
          echo "3.86.156.221 appbackend.lemnisk.co" | sudo tee -a /etc/hosts
        
      - uses: actions/checkout@v1
      - run: npm ci
      
      - name: Run Selenium Tests
        #run: npx mocha --verbose ./test/segmenttest.spec.js || exit 0
        run: |
         npx mocha --version
         npm run test
         #npx mocha -R allure-mocha test/segmenttest.spec.js
        env:
         NODE_ENV: test
        continue-on-error: true
        working-directory: ${{ github.workspace }}

      # - name: Upload Mochawesome Report
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: mochawesome-report
      #     path: /home/runner/work/UIAutomation-Selenium-NodeJS/UIAutomation-Selenium-NodeJS/mochawesome-report
          
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2  
        
      - name: Debugging Information
        run: |
          set -x
          echo "Current Working Directory: $(pwd)"
          echo "Contents of the ./test directory:"
          ls -R ./test
          echo "Environment Variables: ${{ toJson(env) }}"
        continue-on-error: true
