name: Selenium Tests

on:
  push:
    branches:
      - master
      
jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18, 19, 20, 21]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: 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

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Install dependencies
        run: |
          npm install
          npm install mocha --save-dev
          #npm install mocha-selenium
          npm install chai
          #npm install mocha@latest mocha-allure-reporter@latest --save-dev
          npm install --save-dev mochawesome
          npm install -g allure-commandline
          npm install mocha-allure-reporter

      - name: Update /etc/hosts
        run: |
          echo "3.230.10.186 ttl.lemnisk.co" | sudo tee -a /etc/hosts
          echo "3.230.10.186 lemniskapi2.lemnisk.co" | sudo tee -a /etc/hosts
          echo "3.230.10.186 appbackend.lemnisk.co" | sudo tee -a /etc/hosts
        
      - uses: actions/checkout@v1
      - run: npm ci
      
      - name: Run Selenium Tests
        #run: npx mocha --verbose ./test/segmenttest.spec.js || exit 0
        run: npm run test
        #continue-on-error: true
        working-directory: ${{ github.workspace }}

      - name: Debugging Information
        run: |
          echo "Current Working Directory: $(pwd)"
          echo "Contents of the ./test directory:"
          ls -R ./test
          echo "Environment Variables: ${{ toJson(env) }}"
        continue-on-error: true

