name: Selenium Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # This ensures the complete history is fetched, required for private repositories
        token: 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 # Replace with your Personal Access Token

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: |
        npm install
        npm install -g allure-commandline

    - name: Run Selenium Tests
      run: npx mocha -R allure-mocha ./test

    - name: Generate and Open Allure Reports
      run: |
        npx allure generate ./allure-results --clean
        npx allure open ./allure-report
