name: NodeJS with Webpack

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        npx webpack
        
    - name: Install mocha
      run: npm install -g mocha

    - name: Check Mocha version
      run: npx mocha --version
        
    - uses: browser-actions/setup-chrome@v1
    - run: chrome --version

    - name: Run Selenium Tests
      #run: npx mocha --verbose ./test/segmenttest.spec.js || exit 0
      run: npm run test
      env:
        NODE_ENV: test
        continue-on-error: true
        working-directory: ${{ github.workspace }}
        
    - name: Debugging Information
      run: |
        set -x
        echo "Current Working Directory: $(pwd)"
        echo "Contents of the ./test directory:"
        ls -R ./test
        echo "Environment Variables: ${{ toJson(env) }}"
        continue-on-error: true
